//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineKutuphanem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hareket()
        {
            this.Cezalar = new HashSet<Cezalar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<System.DateTime> ALISTARIHI { get; set; }
        public Nullable<System.DateTime> IADETARIHI { get; set; }
        public Nullable<System.DateTime> UYEGETIRTARIH { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cezalar> Cezalar { get; set; }
        public virtual Kitap Kitap1 { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
