//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<int> IPAdress { get; set; }
        public string NameSurname { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
