//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public byte SettingsID { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string FoviconUrl { get; set; }
        public string Author { get; set; }
        public string GoogleAnalytics { get; set; }
        public string FacebookUrl { get; set; }
        public string LinkedinUrl { get; set; }
        public string InstagramUrl { get; set; }
        public string Description { get; set; }
        public string FooterSignature { get; set; }
    }
}
